version: '3.8'

services:
  authorization-service:
    image: ${IMAGE}
    container_name: authorization-service
    ports:
      - "8080:8080" 
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    restart: always